### ISSUE TITLE
Numerous Bugs

### ISSUE THREAD

**Issue by Rawrly85** [jakvike/luckpoints#1]
Foundry Version 0.7.6
TidySheet 0.9.11

1. When you first open a sheet, it shows 2 luck point entries neither of which you can interact with. You need to close and re-open the sheet to get them to work again.
2. If you are a DM and open 2 character sheets, the UI doesn't work. It looks like you are defining the elements by ID rather than class name which results in duplicate IDs showing.

**Comment by jakvike** [comment]
These are fixed with the recent push.  Much appreciated for the heads up.
