### ISSUE TITLE
After attempting to spend an invalid number of points, text field becomes unresponsive

### ISSUE THREAD

**Issue by akrigline** [jakvike/luckpoints#2]
dnd5e 1.1.1
foundry core 0.7.7 (electron)
luck points 0.0.4

Reproduction Steps (GM user):
1. Open a Character sheet, apply some luck points.
2. Go to spend those luck points.
3. Enter in a number higher than the maximum luck points possible.
4. Hit "OK" on the prompt

Expected:
User is able to re-try entering in a new number and hitting enter again.

Actual:
Input no longer responds to changes, hitting enter does nothing.

Recommendation:
Leverage a tiny `FormApplication` instead of appending a textfield to the sheet. Something which pops up and says "How many luck points do you wish to spend?" with a single input. You can tap into the FormApplication's submission logic to verify that the entered value is not higher than the maximum, or use a `range` input to ensure the user can't enter an invalid number to begin with.

**Comment by jakvike** [comment]
This issue has been fixed.  Thank you and appreciate the heads up.
