### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by akrigline** [jakvike/luckpoints#4]
Is there an open source license noted somewhere I am not finding for this repository? I'm interested in implementing similar-but-different mechanics into a different module and was hoping to get a head start by looking through what you've already written.

But if this code is [all rights reserved](https://choosealicense.com/no-permission/) (as implied by having no license), I don't think I should. I just wanted to double check about this.

**Comment by jakvike** [comment]
Please by all means, you are welcome to change it how you please.  It is open-source and free.

**Comment by akrigline** [comment]
> Please by all means, you are welcome to change it how you please. It is open-source and free.

I would greatly appreciate if a LICENSE file was implemented or made note of on the readme to clarify what restrictions/allowances you have in mind.

Here's some common ones in the Foundry VTT Community:
- [MIT](https://choosealicense.com/licenses/mit/)
- [GNU General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/)

Github makes this process pretty easy if you [use the web-UI](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

Thanks for clarifying!

**Comment by jakvike** [comment]
This has been added. Thank you for the info to add the license.
